### PR TITLE
fix(driver): fix build on RHEL 9.3 kernels

### PR DESCRIPTION
**Pull request by iurly**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

> /area build

> /area CI

/area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap-engine-udig

> /area libscap

> /area libpman

> /area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

On recent RHEL9 kernels (namely starting with 5.14.0-327.el9) the kmod driver will fail to build with the following error:

```
./main.c: In function 'scap_init':
./main.c:2896:30: error: assignment to 'char * (*)(const struct device *, umode_t *)' {aka 'char * (*)(const struct device *, short unsigned int *)'} from incompatible pointer type 'char * (*)(struct device *, umode_t *)' {aka 'char * (*)(struct device *, short unsigned int *)'} [-Werror=incompatible-pointer-types]
         g_ppm_class->devnode = ppm_devnode;
                              ^
cc1: all warnings being treated as errors
```

Notice how Red Hat backported that change from kernel 6.2 into what looks like 5.14 for RHEL9.3.

See for instance:
```
$ head -2 */usr/src/kernels/5.14.0-283.el9.x86_64/Makefile.rhelver
RHEL_MAJOR = 9
RHEL_MINOR = 2
```
vs
```
$ head -2 */usr/src/kernels/5.14.0-327.el9.x86_64/Makefile.rhelver
RHEL_MAJOR = 9
RHEL_MINOR = 3
```

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

This is a followup on https://github.com/falcosecurity/libs/pull/919

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Thanks for this fix!
> Notice how Red Hat backported that change from kernel 6.2 into what looks like 5.14 for RHEL9.3.

BUT WHY?? :rofl:

**Comment by deepskyblue86** [comment]
The change: https://github.com/torvalds/linux/commit/ff62b8e6588fb07bedda7423622c140c4edd66a7

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by FedeDP — APPROVED** [review]
/approve
