### ISSUE TITLE
[BUG] scap-driver: fails to compile with kernel 6.3

### ISSUE THREAD

**Issue by hhoffstaette** [falcosecurity/libs#1063]
Trying to rebuild scap-driver against 6.3:

```
CC [M]  /tmp/portage/dev-util/scap-driver-0.29.3-r1/work/libs-e5c53d648f3c4694385bbe488e7d47eaa36c229a_build/driver/src/ppm_fillers.o
In file included from ./include/linux/sched/signal.h:10,
                 from ./include/linux/rcuwait.h:6,
                 from ./include/linux/percpu-rwsem.h:7,
                 from ./include/linux/fs.h:33,
                 from ./include/linux/compat.h:17,
                 from /tmp/portage/dev-util/scap-driver-0.29.3-r1/work/libs-e5c53d648f3c4694385bbe488e7d47eaa36c229a_build/driver/src/ppm_fillers.c:12:
/tmp/portage/dev-util/scap-driver-0.29.3-r1/work/libs-e5c53d648f3c4694385bbe488e7d47eaa36c229a_build/driver/src/ppm_fillers.c: In function 'f_proc_startupdate':
./include/linux/cred.h:378:23: error: passing argument 1 of 'inode_permission' from incompatible pointer type [-Werror=incompatible-pointer-types]
  378 |         current_cred()->xxx;                    \
      |                       ^
      |                       |
      |                       struct user_namespace *
./include/linux/cred.h:395:34: note: in expansion of macro 'current_cred_xxx'
  395 | #define current_user_ns()       (current_cred_xxx(user_ns))
      |                                  ^~~~~~~~~~~~~~~~
/tmp/portage/dev-util/scap-driver-0.29.3-r1/work/libs-e5c53d648f3c4694385bbe488e7d47eaa36c229a_build/driver/src/ppm_fillers.c:1250:67: note: in expansion of macro 'current_user_ns'
 1250 |                                 exe_writable |= (inode_permission(current_user_ns(), file_inode(exe_file), MAY_WRITE) == 0);
      |                                                                   ^~~~~~~~~~~~~~~
./include/linux/fs.h:2476:22: note: expected 'struct mnt_idmap *' but argument is of type 'struct user_namespace *'
 2476 | int inode_permission(struct mnt_idmap *, struct inode *, int);
      |                      ^~~~~~~~~~~~~~~~~~
./include/linux/cred.h:378:23: error: passing argument 1 of 'inode_owner_or_capable' from incompatible pointer type [-Werror=incompatible-pointer-types]
  378 |         current_cred()->xxx;                    \
      |                       ^
      |                       |
      |                       struct user_namespace *
./include/linux/cred.h:395:34: note: in expansion of macro 'current_cred_xxx'
  395 | #define current_user_ns()       (current_cred_xxx(user_ns))
      |                                  ^~~~~~~~~~~~~~~~
/tmp/portage/dev-util/scap-driver-0.29.3-r1/work/libs-e5c53d648f3c4694385bbe488e7d47eaa36c229a_build/driver/src/ppm_fillers.c:1251:72: note: in expansion of macro 'current_user_ns'
 1251 |                                 exe_writable |= inode_owner_or_capable(current_user_ns(), file_inode(exe_file));
      |                                                                        ^~~~~~~~~~~~~~~
./include/linux/fs.h:1607:47: note: expected 'struct mnt_idmap *' but argument is of type 'struct user_namespace *'
 1607 | bool inode_owner_or_capable(struct mnt_idmap *idmap,
      |                             ~~~~~~~~~~~~~~~~~~^~~~~
cc1: some warnings being treated as errors
```

I have not investigated further yet.

**Comment by FedeDP** [comment]
Hi! Thanks for opening this issue!
Our ci actually is lagging behind because it ensures that we are able to build latest archlinux kernel, but arch is still at 6.2.12 (at least this morning).
We are gonna look at this and fix it asap!

**Comment by hhoffstaette** [comment]
It looks like this was caused by [abf08576](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=abf08576afe31506b812c8c1be9714f78613f300) or related followups.

**Comment by FedeDP** [comment]
Ok arch upgraded the linux kernel package ;) And our daily CI job started failing indeed: https://github.com/falcosecurity/libs/actions/workflows/latest-kernel.yml

I am going to work on this asap!

**Comment by FedeDP** [comment]
A PR with the fixes has been opened :)

**Comment by hhoffstaette** [comment]
> A PR with the fixes has been opened, see #1071 :)

All that macro mess and bitshifted typecasts are insane. Thanks SO much for this!

**Comment by hhoffstaette** [comment]
I managed to backport the relevant bit to the older driver we have in Gentoo and it now builds & works correctly on 6.3.1. :raised_hands:
