### PR TITLE
fix(driver): fix build on RHEL 8.9 kernels

### PR DESCRIPTION
**Pull request by iurly**
On recent RHEL8 kernels (namely starting with 4.18.0-506.el8) the kmod driver will fail to build with the following error:

```
  CC [M]  /code/sysdig-rw/main.o
/code/sysdig-rw/main.c: In function 'scap_init':
/code/sysdig-rw/main.c:2897:23: error: assignment to 'char * (*)(const struct device *, umode_t *)' {aka 'char * (*)(const struct device *, short unsigned int *)'} from incompatible pointer type 'char * (*)(struct device *, umode_t *)' {aka 'char * (*)(struct device *, short unsigned int *)'} [-Werror=incompatible-pointer-types]
 2897 |  g_ppm_class->devnode = ppm_devnode;
      |                       ^
cc1: some warnings being treated as errors
```

Notice how Red Hat backported that change from kernel 6.2 into what looks like 4.18 for RHEL8.9, a few months after backporting it into 5.14 for RHEL9.3.

So add the corresponding check, making sure not to break RHEL9.0-9.2 which DO NOT contain such change.

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

> /area build

> /area CI

/area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap-engine-udig

> /area libscap

> /area libpman

> /area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by LucaGuerra — APPROVED** [review]
Thank you for this!

**Review by FedeDP — APPROVED** [review]
/approve
