### PR TITLE
fix(driver): fixed 6.3 kernel build and verifier issues.

### LINKED ISSUE #1063: [BUG] scap-driver: fails to compile with kernel 6.3
Trying to rebuild scap-driver against 6.3:

```
CC [M]  /tmp/portage/dev-util/scap-driver-0.29.3-r1/work/libs-e5c53d648f3c4694385bbe488e7d47eaa36c229a_build/driver/src/ppm_fillers.o
In file included from ./include/linux/sched/signal.h:10,
                 from ./include/linux/rcuwait.h:6,
                 from ./include/linux/percpu-rwsem.h:7,
                 from ./include/linux/fs.h:33,
                 from ./include/linux/compat.h:17,
                 from /tmp/portage/dev-util/scap-driver-0.29.3-r1/work/libs-e5c53d648f3c4694385bbe488e7d47eaa36c229a_build/driver/src/ppm_fillers.c:12:
/tmp/portage/dev-util/scap-driver-0.29.3-r1/work/libs-e5c53d648f3c4694385bbe488e7d47eaa36c229a_build/driver/src/ppm_fillers.c: In function 'f_proc_startupdate':
./include/linux/cred.h:378:23: error: passing argument 1 of 'inode_permission' from incompatible pointer type [-Werror=incompatible-pointer-types]
  378 |         current_cred()->xxx;                    \
      |                       ^
      |                       |
      |                       struct user_namespace *
./include/linux/cred.h:395:34: note: in expansion of macro 'current_cred_xxx'
  395 | #define current_user_ns()       (current_cred_xxx(user_ns))
      |                                  ^~~~~~~~~~~~~~~~
/tmp/portage/dev-util/scap-driver-0.29.3-r1/work/libs-e5c53d648f3c4694385bbe488e7d47eaa36c229a_build/driver/src/ppm_fillers.c:1250:67: note: in expansion of macro 'current_user_ns'
 1250 |                                 exe_writable |= (inode_permission(current_user_ns(), file_inode(exe_file), MAY_WRITE) == 0);
      |                                                                   ^~~~~~~~~~~~~~~
./include/linux/fs.h:2476:22: note: expected 'struct mnt_idmap *' but argument is of type 'struct user_namespace *'
 2476 | int inode_permission(struct mnt_idmap *, struct inode *, int);
      |                      ^~~~~~~~~~~~~~~~~~
./include/linux/cred.h:378:23: error: passing argument 1 of 'inode_owner_or_capable' from incompatible pointer type [-Werror=incompatible-pointer-types]
  378 |         current_cred()->xxx;                    \
      |                       ^
      |                       |
      |                       struct user_namespace *
./include/linux/cred.h:395:34: note: in expansion of macro 'current_cred_xxx'
  395 | #define current_user_ns()       (current_cred_xxx(user_ns))
      |                                  ^~~~~~~~~~~~~~~~
/tmp/portage/dev-util/scap-driver-0.29.3-r1/work/libs-e5c53d648f3c4694385bbe488e7d47eaa36c229a_build/driver/src/ppm_fillers.c:1251:72: note: in expansion of macro 'current_user_ns'
 1251 |                                 exe_writable |= inode_owner_or_capable(current_user_ns(), file_inode(exe_file));
      |                                                                        ^~~~~~~~~~~~~~~
./include/linux/fs.h:1607:47: note: expected 'struct mnt_idmap *' but argument is of type 'struct user_namespace *'
 1607 | bool inode_owner_or_capable(struct mnt_idmap *idmap,
      |                             ~~~~~~~~~~~~~~~~~~^~~~~
cc1: some warnings being treated as errors
```

I have not investigated further yet.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area driver-kmod
/area driver-bpf
/area driver-modern-bpf

**Does this PR require a change in the driver versions?**

/version driver-API-version-patch

**What this PR does / why we need it**:

It fixes issues with the 6.3 kernel.

**Which issue(s) this PR fixes**:

Fixes #1063 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix(driver): fix build and verifier for linux 6.3.
```

### CODE REVIEW

**Review by LucaGuerra — APPROVED** [review]
LGTM

**Review by leogr — APPROVED** [review]
