### PR TITLE
fix(driver): fix build on linux-6.2

### LINKED ISSUE #918: [BUG] scap-driver: compilation failure with kernel 6.2.0
(previous sysdig contributor & Gentoo maintainer here :)

The old-style scap driver fails to build against kernel 6.2.0:
```
  CC [M]  /tmp/portage/dev-util/scap-driver-0.29.3/work/libs-e5c53d648f3c4694385bbe488e7d47eaa36c229a_build/driver/src/main.o
/tmp/portage/dev-util/scap-driver-0.29.3/work/libs-e5c53d648f3c4694385bbe488e7d47eaa36c229a_build/driver/src/main.c: In function 'scap_init':
/tmp/portage/dev-util/scap-driver-0.29.3/work/libs-e5c53d648f3c4694385bbe488e7d47eaa36c229a_build/driver/src/main.c:2501:30: error: assignment to 'char * (*)(const struct device *, umode_t *)' {aka 'char * (*)(const struct device *, short unsigned int *)'} from incompatible pointer type 'char * (*)(struct device *, umode_t *)' {aka 'char * (*)(struct device *, short unsigned int *)'} [-Werror=incompatible-pointer-types]
 2501 |         g_ppm_class->devnode = ppm_devnode;
      |                              ^
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:252: /tmp/portage/dev-util/scap-driver-0.29.3/work/libs-e5c53d648f3c4694385bbe488e7d47eaa36c229a_build/driver/src/main.o] Error 1
make[1]: *** [Makefile:2021: /tmp/portage/dev-util/scap-driver-0.29.3/work/libs-e5c53d648f3c4694385bbe488e7d47eaa36c229a_build/driver/src] Error 2
make[1]: Leaving directory '/tmp/linux-6.2.0'
```
This cryptic message stems from the fact that apparently some attributes of the `struct device` returned from class_create() are const since 6.2 and the conditional `ppm_devnode` prototypes no longer match, since they are declared to take a non-const `struct device*`.
The fix is easy: more `#ifdef`s :laughing:

### PR DESCRIPTION
**Pull request by hhoffstaette**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area driver-kmod

**What this PR does / why we need it**:

Attributes in "struct device*" are const since kernel-6.2, so add a matching prototype for ppm_devnode().

**Which issue(s) this PR fixes**:

Fixes #918 

**Special notes for your reviewer**:

Not sure about the driver version/ABI compatibility. Shouldn't impact ABI but then I don't really know whether a driver built for 6.1 is expected to work on 6.2. :shrug: 

```release-note
fix(driver): fixed kmod build on kernel >= 6.2
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Yay! Thank you for taking the time to open this one!

**Comment by FedeDP** [comment]
Can confirm the issue building `6.2.arch-1` using driverkit:
```
DEBU   CC [M]  /tmp/driver/main.o
DEBU -/tmp/driver/main.c: In function 'scap_init':
DEBU �/tmp/driver/main.c:2815:30: error: assignment to 'char * (*)(const struct device *, umode_t *)' {aka 'char * (*)(const struct device *, short unsigned int *)'} from incompatible pointer type 'char * (*)(struct device *, umode_t *)' {aka 'char * (*)(struct device *, short unsigned int *)'} [-Werror=incompatible-pointer-types]
DEBU  2815 |         g_ppm_class->devnode = ppm_devnode;
DEBU       |                              ^
DEBU +cc1: some warnings being treated as errors
DEBU Fmake[2]: *** [scripts/Makefile.build:252: /tmp/driver/main.o] Error 1
DEBU 2make[1]: *** [Makefile:2021: /tmp/driver] Error 2
DEBU )make[1]: Leaving directory '/tmp/kernel'
DEBU $make: *** [Makefile:7: all] Error 2
DEBU log pipe close                                error=EOF
```

And the fix, with the patch:
```
DEBU   CC [M]  /tmp/driver/main.o
DEBU -  CC [M]  /tmp/driver/dynamic_params_table.o
DEBU &  CC [M]  /tmp/driver/fillers_table.o
DEBU $  CC [M]  /tmp/driver/flags_table.o
DEBU #  CC [M]  /tmp/driver/ppm_events.o
DEBU $  CC [M]  /tmp/driver/ppm_fillers.o
DEBU $  CC [M]  /tmp/driver/event_table.o
DEBU &  CC [M]  /tmp/driver/syscall_table.o
DEBU $  CC [M]  /tmp/driver/ppm_cputime.o
DEBU !  CC [M]  /tmp/driver/tp_table.o
DEBU   LD [M]  /tmp/driver/falco.o
DEBU %  MODPOST /tmp/driver/Module.symvers
DEBU "  CC [M]  /tmp/driver/falco.mod.o
DEBU   LD [M]  /tmp/driver/falco.ko
DEBU   BTF [M] /tmp/driver/falco.ko
DEBU )make[1]: Leaving directory '/tmp/kernel'
DEBU $+ mv falco.ko /tmp/driver/module.ko
DEBU !+ strip -g /tmp/driver/module.ko
DEBU  + modinfo /tmp/driver/module.ko
DEBU �filename:       /tmp/driver/module.ko
DEBU schema_version: 2.3.0
DEBU api_version:    4.0.0
DEBU build_commit:   92ee159052eb24ed6fe38725f1967ce50fd27c9b
DEBU version:        92ee159052eb24ed6fe38725f1967ce50fd27c9b
DEBU author:         the Falco authors
DEBU license:        GPL
DEBU srcversion:     862153984502496F2DEFF2D
DEBU depends:
DEBU retpoline:      Y
DEBU name:           falco
DEBU vermagic:       6.2.0-arch1-1 SMP preempt mod_unload
DEBU parm:           g_buffer_bytes_dim:This is the dimension of a single per-CPU buffer in bytes. Please note: this buffer will be mapped twice in the process virtual memory, so pay attention to its size.
DEBU parm:           max_consumers:Maximum number of consumers that can simultaneously open the devices (uint)
DEBU parm:           verbose:Enable verbose logging (bool)
```

Thank you very much!

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
And, as promised, here is a new ci job that tests daily against latest kernel available on arch: https://github.com/falcosecurity/libs/pull/920

**Review by Andreagit97 — APPROVED** [review]
thank you!
/approve
