### PR TITLE
fix(kmod): fix `kmod` build on some kernels

### PR DESCRIPTION
**Pull request by Andreagit97**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area driver-kmod

**Does this PR require a change in the driver versions?**

No

**What this PR does / why we need it**:

This PR introduces 2 main fixes in the kmod:

1. The changes introduced here https://github.com/falcosecurity/libs/pull/640 break the build on very old kernels:

```
DEBU �In file included from /tmp/driver/ppm_events.c:89:0:
DEBU /tmp/driver/ppm_events_public.h: At top level:
DEBU /tmp/driver/ppm_events_public.h:19:7: warning: "__USE_VMLINUX__" is not defined [-Wundef]
DEBU  #elif __USE_VMLINUX__
DEBU        ^
DEBU Z/tmp/driver/ppm_events.c: In function 'sock_getname':
DEBU /tmp/driver/ppm_events.c:264:13: error: 'struct inet_sock' has no member named 'inet_dport'
DEBU     if (!inet->inet_dport ||
DEBU              ^
DEBU /tmp/driver/ppm_events.c:268:24: error: 'struct inet_sock' has no member named 'inet_dport'
DEBU     sin->sin_port = inet->inet_dport;
DEBU                         ^
DEBU �/tmp/driver/ppm_events.c:269:31: error: 'struct inet_sock' has no member named 'inet_daddr'
DEBU     sin->sin_addr.s_addr = inet->inet_daddr;
DEBU                                ^
DEBU �/tmp/driver/ppm_events.c:271:19: error: 'struct inet_sock' has no member named 'inet_rcv_saddr'
DEBU     u32 addr = inet->inet_rcv_saddr;
DEBU                    ^
DEBU �/tmp/driver/ppm_events.c:273:16: error: 'struct inet_sock' has no member named 'inet_saddr'
DEBU      addr = inet->inet_saddr;
DEBU                 ^
DEBU �/tmp/driver/ppm_events.c:275:24: error: 'struct inet_sock' has no member named 'inet_sport'
DEBU     sin->sin_port = inet->inet_sport;
DEBU                         ^
DEBU �/tmp/driver/ppm_events.c:288:14: error: 'struct inet_sock' has no member named 'inet_dport'
DEBU     if ((!inet->inet_dport) ||
DEBU               ^
DEBU �/tmp/driver/ppm_events.c:292:25: error: 'struct inet_sock' has no member named 'inet_dport'
DEBU     sin->sin6_port = inet->inet_dport;
DEBU                          ^
DEBU �/tmp/driver/ppm_events.c:293:23: error: 'struct sock' has no member named 'sk_v6_daddr'
DEBU     sin->sin6_addr = sk->sk_v6_daddr;
DEBU                        ^
DEBU �/tmp/driver/ppm_events.c:295:23: error: 'struct sock' has no member named 'sk_v6_rcv_saddr'
DEBU     sin->sin6_addr = sk->sk_v6_rcv_saddr;
DEBU                        ^
DEBU �/tmp/driver/ppm_events.c:299:25: error: 'struct inet_sock' has no member named 'inet_sport'
DEBU     sin->sin6_port = inet->inet_sport;
```

As you can see some fields used in the PR are not defined (`sk_v6_rcv_saddr`, `inet_sport`, `inet_dport`)

2. The `module_param_call` requires a different signature for the `set` function on different kernels and this cause some build problems. To fix it we use the `module_param_cb` that has had a stable interface since `2.36.6`. You can find more info here https://github.com/falcosecurity/libs/pull/652#discussion_r986767444

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

Tested on:
* 4.14.276-211.499.amzn2.x86_64 (x86)
* 5.11.0-051100-generic (x86)
* 5.15.0-33-generic (x86)
* 5.15.0-1009-aws (aarch64)
* 5.11.0-051100-generic (s390x)

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
Can confirm this builds on 2.6.32.
/approve

On a side note, we should **really** add a driverkit test job to the libs CI, to test multiple kernel versions (at least the build).

**Review by LucaGuerra — DISMISSED** [review]
lgtm

**Review by FedeDP — APPROVED** [review]
/approve

File: driver/main.c [hunk 1]
```diff
@@ -2972,7 +2972,15 @@ static int set_g_buffer_bytes_dim(const char *val, const struct kernel_param *kp
...
 
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(2, 6, 36)
+static const struct kernel_param_ops g_buffer_bytes_dim_ops = {
+	.set	= set_g_buffer_bytes_dim,
+	.get	= param_get_ulong,
+};
+module_param_cb(g_buffer_bytes_dim, &g_buffer_bytes_dim_ops, &g_buffer_bytes_dim, 0644);
+#else
 module_param_call(g_buffer_bytes_dim, set_g_buffer_bytes_dim, param_get_ulong, &g_buffer_bytes_dim, 0644);
+#endif
```
Comment (Andreagit97) [inline driver/main.c:2983]: Here we have introduced the `kernel_param_ops` because it has a stable interface https://elixir.bootlin.com/linux/v2.6.36/source/include/linux/moduleparam.h#L34
The problem with using directly the `module_param_call` is that the prototype of the `set` method is changed over time
 in some kernel versions (like 2.6.36) is:

 int (*[oldset](https://elixir.bootlin.com/linux/v2.6.36/C/ident/oldset))(const char *, struct [kernel_param](https://elixir.bootlin.com/linux/v2.6.36/C/ident/kernel_param) *);

like in recent kernel versions like (5.11) we pass through the `kernel_param_ops` as you can see here https://elixir.bootlin.com/linux/v5.11/source/include/linux/moduleparam.h#L297, so we have this signature:

int (*[set](https://elixir.bootlin.com/linux/v5.11/C/ident/set))(const char *val, const struct [kernel_param](https://elixir.bootlin.com/linux/v5.11/C/ident/kernel_param) *[kp](https://elixir.bootlin.com/linux/v5.11/C/ident/kp));

Comment (Andreagit97) [reply driver/main.c:2983]: So using always something like `static int set_g_buffer_bytes_dim(const char *val, const struct kernel_param *kp)` we have no problems because in kernels <= `2.6.36` the `const` qualifier won't be used but the build will be successful

**Review by jcpittman144 — CHANGES_REQUESTED** [review]
Regarding the LINUX_VERSION_CODE check to avoid calling sock->ops->getname():
I think we need to use the new manual logic for any kernel version >= 5.8.
Because in 5.8, a change was introduced into inet_getname(), to call BPF_CGROUP_RUN_SA_PROG_LOCK() if cgroup_bpf_enabled is true; and BPF_CGROUP_RUN_SA_PROG_LOCK() may call the offending lock_sock() function.

**Comment by Andreagit97** [comment]
> Regarding the LINUX_VERSION_CODE check to avoid calling sock->ops->getname():
I think we need to use the new manual logic for any kernel version >= 5.8.
Because in 5.8, a change was introduced into inet_getname(), to call BPF_CGROUP_RUN_SA_PROG_LOCK() if cgroup_bpf_enabled is true; and BPF_CGROUP_RUN_SA_PROG_LOCK() may call the offending lock_sock() function.

ty @jcpittman144!

**Review by FedeDP — APPROVED** [review]
/approve

**Review by LucaGuerra — APPROVED** [review]
lgtm
