### PR TITLE
bpf: fix build on some kernels

### PR DESCRIPTION
**Pull request by alban**
Signed-off-by: Alban Crequy <albancrequy@microsoft.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area driver-kmod

/area driver-ebpf

> /area libscap

> /area libsinsp

> /area tests

> /area proposals

**What this PR does / why we need it**:

This PR makes the bpf code compile on kernel 5.13.0-1023-azure (Ubuntu 20.04.4 LTS)

On some new kernels, the bpf code does not compile because some kernel headers expect KBUILD_MODNAME to be defined.

Tested on Ubuntu 20.04.4 LTS with Linux 5.13.0-1023-azure.

Symptoms:

```
In file included from /.../sysdig/bpf/probe.c:22:
In file included from /.../sysdig/bpf/filler_helpers.h:13:
In file included from ./include/net/sock.h:59:
In file included from ./include/linux/filter.h:27:
In file included from ./include/net/sch_generic.h:21:
./include/net/flow_offload.h:324:4: error: use of undeclared identifier 'KBUILD_MODNAME'
                        NL_SET_ERR_MSG_MOD(extack, "Mixing HW stats types for actions is not supported");
                        ^
./include/linux/netlink.h:102:27: note: expanded from macro 'NL_SET_ERR_MSG_MOD'
        NL_SET_ERR_MSG((extack), KBUILD_MODNAME ": " msg)
```

Our BPF code does not use the functions using KBUILD_MODNAME, so it is safe to set it to an arbitrary value to make it compile.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Wow thank you very much! I love tiny yet important fixes :)

/cc @Andreagit97 
/ok-to-test

File: driver/bpf/Makefile [hunk 1]
```diff
@@ -56,6 +56,7 @@ $(obj)/probe.o: $(src)/probe.c \
 		$(DEBUG) \
 		-D__KERNEL__ \
 		-D__BPF_TRACING__ \
+		-DKBUILD_MODNAME='"falcobpf"' \
```
Comment (deepskyblue86) [inline driver/bpf/Makefile:59]: If I grep `KBUILD_MODNAME` I see:
```
driver/driver_config.h.in:31:#ifndef KBUILD_MODNAME
driver/driver_config.h.in:32:#define KBUILD_MODNAME DRIVER_NAME
```
Maybe we should have a .in file here too, and follow what's currently done for driver/Makefile.in putting `@DRIVER_NAME@` for it

Comment (FedeDP) [reply driver/bpf/Makefile:59]: I don't think that's actually needed; current `driver_config.h`:
```
...
#include "ppm_api_version.h"

#define DRIVER_VERSION "2.0.0-449+3f5c13b-driver"

#define DRIVER_NAME "scap"

#define DRIVER_DEVICE_NAME "scap"

#define DRIVER_COMMIT "3f5c13b6827a786d802ccc540998b48fc9a97a4a"

#ifndef KBUILD_MODNAME
#define KBUILD_MODNAME DRIVER_NAME
#endif
```

KBUILD_MODNAME should be actually set with no issues to "scap".

Comment (deepskyblue86) [reply driver/bpf/Makefile:59]: @alban would you mind sharing your build steps? FWIW I had some issues in the past with `driver_config.h` being in the gitignore and not noticing it wasn't the one I was expecting because of different config / reconfig attempts.
