### PR TITLE
Avoid calls to sock->getname() from kernel module fillers

### PR DESCRIPTION
**Pull request by jcpittman144**
Filler functions run under RCU read lock, where use of blocking locks (or any reschedule) is forbidden.  Filler functions currently call sock->getname(), but this is unsafe because in some kernel versions, inet_getname() uses blocking locks; this results in loss of lock protection, and specifically a use-after-free kernel panic due to ppm_release() freeing a consumer object while it is still in use by the tracepoint handler/filler function.

Solution is to follow the method used by the eBPF probe, and use private logic to retrieve the necessary information from the socket.

Signed-off-by: Joseph Pittman <joseph.pittman@sysdig.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

> /area build

> /area CI

/area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap-engine-udig

> /area libscap

> /area libpman

> /area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

Avoid use of calls to sock->getname() from tracepoint handlers/filler functions, because
sock->getname() may use blocking locks in some Linux kernels, thus violating the
requirements of the RCU read lock environment in which the tracepoint handler functions
operate.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix: avoid unsafe calls to socket getname from filler functions.
```

### CODE REVIEW

**Comment by FedeDP** [comment]
This is the commit that introduced the lock: https://github.com/torvalds/linux/commit/9dfc685e0262d4c5e44e13302f89841fa75173ca (merged in 5.16.0-rc1).

**Review by FedeDP — APPROVED** [review]
Can confirm that the code is the same we use in `bpf_getsockname`; IMHO this MUST be merged.
/approve

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
Unfortunately this breaks build on 2.6.32 kernels:
```
DEBU �In file included from /tmp/driver/ppm_events.c:89:0:
DEBU /tmp/driver/ppm_events_public.h: At top level:
DEBU /tmp/driver/ppm_events_public.h:19:7: warning: "__USE_VMLINUX__" is not defined [-Wundef]
DEBU  #elif __USE_VMLINUX__
DEBU        ^
DEBU Z/tmp/driver/ppm_events.c: In function 'sock_getname':
DEBU /tmp/driver/ppm_events.c:264:13: error: 'struct inet_sock' has no member named 'inet_dport'
DEBU     if (!inet->inet_dport ||
DEBU              ^
DEBU /tmp/driver/ppm_events.c:268:24: error: 'struct inet_sock' has no member named 'inet_dport'
DEBU     sin->sin_port = inet->inet_dport;
DEBU                         ^
DEBU �/tmp/driver/ppm_events.c:269:31: error: 'struct inet_sock' has no member named 'inet_daddr'
DEBU     sin->sin_addr.s_addr = inet->inet_daddr;
DEBU                                ^
DEBU �/tmp/driver/ppm_events.c:271:19: error: 'struct inet_sock' has no member named 'inet_rcv_saddr'
DEBU     u32 addr = inet->inet_rcv_saddr;
DEBU                    ^
DEBU �/tmp/driver/ppm_events.c:273:16: error: 'struct inet_sock' has no member named 'inet_saddr'
DEBU      addr = inet->inet_saddr;
DEBU                 ^
DEBU �/tmp/driver/ppm_events.c:275:24: error: 'struct inet_sock' has no member named 'inet_sport'
DEBU     sin->sin_port = inet->inet_sport;
DEBU                         ^
DEBU �/tmp/driver/ppm_events.c:288:14: error: 'struct inet_sock' has no member named 'inet_dport'
DEBU     if ((!inet->inet_dport) ||
DEBU               ^
DEBU �/tmp/driver/ppm_events.c:292:25: error: 'struct inet_sock' has no member named 'inet_dport'
DEBU     sin->sin6_port = inet->inet_dport;
DEBU                          ^
DEBU �/tmp/driver/ppm_events.c:293:23: error: 'struct sock' has no member named 'sk_v6_daddr'
DEBU     sin->sin6_addr = sk->sk_v6_daddr;
DEBU                        ^
DEBU �/tmp/driver/ppm_events.c:295:23: error: 'struct sock' has no member named 'sk_v6_rcv_saddr'
DEBU     sin->sin6_addr = sk->sk_v6_rcv_saddr;
DEBU                        ^
DEBU �/tmp/driver/ppm_events.c:299:25: error: 'struct inet_sock' has no member named 'inet_sport'
DEBU     sin->sin6_port = inet->inet_sport;
DEBU                          ^
DEBU Lmake[2]: *** [scripts/Makefile.build:230: /tmp/driver/ppm_events.o] Error 1
```
