### PR TITLE
fix(driver): use configure system to check for mnt_idmap for fs

### PR DESCRIPTION
**Pull request by deepskyblue86**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area driver-kmod

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:
Kernel 6.3 changed fs functions to `struct mnt_idmap`.
Use the configure system in place of the version check to support driver build on RHEL 9 (namely 5.14.0-547.el9.x86_64).

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
```c
./include/linux/fs.h:3027:22: note: expected 'struct mnt_idmap *' but argument is of type 'struct user_namespace *'
 3027 | int inode_permission(struct mnt_idmap *, struct inode *, int);
      |                      ^~~~~~~~~~~~~~~~~~
./include/linux/cred.h:378:23: error: passing argument 1 of 'inode_owner_or_capable' from incompatible pointer type [-Werror=incompatible-pointer-types]
```

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
Love this, thanks!
/approve

**Review by FedeDP — CHANGES_REQUESTED** [review]
Uh CI is not happy; looking into it.

**Review by LucaGuerra — APPROVED** [review]

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
> Please double check driver/SCHEMA_VERSION file. See [versioning](https://github.com/falcosecurity/libs/blob/master/driver/README.VERSION.md#schema-version-number).

False positive.
/unhold

**Review by LucaGuerra — APPROVED** [review]
