### ISSUE TITLE
cannot build scap driver scap/8.0.0+driver for 6.17.0-5-generic on ubuntu server 25.10

### ISSUE THREAD

**Issue by devZer0** [falcosecurity/libs#2716]
i am trying to use sysdig on ubuntu server 25.10 and installation of sysdig package fails with the errors below.

```
# apt install sysdig

Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  linux-headers-6.17.0-5-generic  linux-modules-6.17.0-5-generic  linux-tools-6.17.0-5  linux-tools-6.17.0-5-generic
Verwenden Sie »apt autoremove«, um sie zu entfernen.

Installiere:
  sysdig

Zusammenfassung:
  Aktualisiere: 0, Installiere: 1, Entferne: 0, Aktualisiere nicht: 0
  Herunterlade-Größe: 0 B / 15,7 MB
  Benötigter Platz: 48,9 MB / 7.883 MB verfügbar

Vormals nicht ausgewähltes Paket sysdig wird gewählt.
(Lese Datenbank ... 134954 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../sysdig_0.40.1-rc2_amd64.deb ...
Entpacken von sysdig (0.40.1-rc2) ...
sysdig (0.40.1-rc2) wird eingerichtet ...
Loading new scap/8.0.0+driver DKMS files...
Building for 6.17.0-5-generic and 6.17.0-6-generic

Building initial module scap/8.0.0+driver for 6.17.0-5-generic
Sign command: /usr/bin/kmodsign
Binary update-secureboot-policy not found, modules won't be signed

Building module(s)....(bad exit status: 2)
Failed command:
make -j4 KERNELRELEASE=6.17.0-5-generic -C /lib/modules/6.17.0-5-generic/build M=/var/lib/dkms/scap/8.0.0+driver/build
/usr/share/apport/package-hooks/dkms_packages.py:101: DeprecationWarning: apport.fatal() is deprecated. Please use apport.logging.fatal() directly instead.
  apport.fatal('Cannot create report: ' + str(e))
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/sysdig.0.crash'

Error! Bad return status for module build on kernel: 6.17.0-5-generic (x86_64)
Consult /var/lib/dkms/scap/8.0.0+driver/build/make.log for more information.
dpkg: Fehler beim Bearbeiten des Paketes sysdig (--configure):
 »installiertes post-installation-Skript des Paketes sysdig«-Unterprozess gab den Fehlerwert 10 zurück
Trigger für man-db (2.13.1-1) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 sysdig
needrestart is being skipped since dpkg has failed
Fehler: Sub-process /usr/bin/dpkg returned an error code (1)
```

apparently , the module code is not compatible with the current 6.17 kernel 

```
# cat /var/lib/dkms/scap/8.0.0+driver/build/make.log|grep -A2 error
ppm_events.c:91:54: error: macro ‘access_ok’ passed 3 arguments, but takes just 2
   91 |         if(likely(ppm_access_ok(VERIFY_READ, from, n)))
      |                                                      ^
--
ppm_events.c:50:41: error: ‘access_ok’ undeclared (first use in this function)
   50 | #define ppm_access_ok(type, addr, size) access_ok(type, addr, size)
      |                                         ^~~~~~~~~
--
ppm_events.c:127:67: error: macro ‘access_ok’ passed 3 arguments, but takes just 2
  127 |                 if(!ppm_access_ok(VERIFY_READ, from, bytes_to_read)) {
      |                                                                   ^
--
/usr/src/linux-headers-6.17.0-5-generic/include/linux/init.h:182:22: error: passing argument 1 of ‘class_create’ from incompatible pointer type [-Wincompatible-pointer-types]
  182 | #define THIS_MODULE (&__this_module)
      |                     ~^~~~~~~~~~~~~~~
--
main.c:2893:23: error: too many arguments to function ‘class_create’; expected 1, have 2
 2893 |         g_ppm_class = class_create(THIS_MODULE, DRIVER_DEVICE_NAME);
      |                       ^~~~~~~~~~~~
--
main.c:2904:30: error: assignment to ‘char * (*)(const struct device *, umode_t *)’ {aka ‘char * (*)(const struct device *, short unsigned int *)’} from incompatible pointer type ‘char * (*)(struct device *, umode_t *)’ {aka ‘char * (*)(struct device *, short unsigned int *)’} [-Wincompatible-pointer-types]
 2904 |         g_ppm_class->devnode = ppm_devnode;
      |                              ^
--
ppm_events.c:50:41: error: ‘access_ok’ undeclared (first use in this function)
   50 | #define ppm_access_ok(type, addr, size) access_ok(type, addr, size)
      |                                         ^~~~~~~~~
```

cannot run sysdig afterwards:

```
# sysdig
Unable to load the driver
error opening device /dev/scap0. Make sure you have root credentials and that the scap module is loaded: No such file or directory
```

here is the full make.log :

https://pastebin.com/3MZZGrAY

```
# uname -a
Linux ubuntu2510-server 6.17.0-6-generic #6-Ubuntu SMP PREEMPT_DYNAMIC Tue Oct  7 13:34:17 UTC 2025 x86_64 GNU/Linux
```

**Comment by devZer0** [comment]
apparently , there is already an open ticket https://github.com/draios/sysdig/issues/2151

**Comment by ekoops** [comment]
Hey, I checked https://github.com/draios/sysdig/issues/2151 and it should work on your setup now. Could you please check it?

**Comment by devZer0** [comment]
hello, thank you, i have tested it with 6.17.0-7-generic kernel and it works now.  thank you very much !
